# The name of the executables
SERVER = server
CLIENT = client

# Compilation flags
CC = cc
CFLAGS = -Wall -Wextra -Werror

# Command to remove files/directories
REMOVE = rm -rf
# Command to create directories
MKDIR = mkdir -p

# Path variables
SRCS_PATH =  ./srcs/
OBJS_PATH = ./objs/
BONUS_PATH = ./srcs_bonus/
LIBS_PATH = ./libs/
HEADER_PATH = ./include/

# Path to libraries
LIBFT_PATH = $(LIBS_PATH)libft/

# Source files
SERVER_SRCS_FILES = server.c utils.c
CLIENT_SRCS_FILES = client.c utils.c

# Object files
SERVER_OBJS = $(addprefix $(OBJS_PATH), $(SERVER_SRCS_FILES:.c=.o))
CLIENT_OBJS = $(addprefix $(OBJS_PATH), $(CLIENT_SRCS_FILES:.c=.o))

# All object files
OBJ = $(SERVER_OBJS) $(CLIENT_OBJS)	

# Compiler flags to include library headers
INCLUDES = -I $(HEADER_PATH) -I $(LIBFT_PATH)includes/
# Compiler flags to link to libraries
LIBS = -L$(LIBFT_PATH) -lft

# Color codes for terminal output
DEF_COLOR = \033[0;39m
GRAY = \033[0;90m
RED = \033[0;91m
GREEN = \033[0;92m
YELLOW = \033[0;93m
BLUE = \033[0;94m
MAGENTA = \033[0;95m
CYAN = \033[0;96m
WHITE = \033[0;97m

# The default target calling for both executables
all : $(SERVER) $(CLIENT)

# The target to build the server
$(SERVER) : $(SERVER_OBJS)
	@make -C $(LIBFT_PATH) --no-print-directory
	@$(CC) $(CFLAGS) $(SERVER_OBJS) -o $(SERVER) $(LIBS)
	@echo "$(GREEN)[MINITALK] Server compiled successfully!$(DEF_COLOR)"

# The target to build the client
$(CLIENT) : $(CLIENT_OBJS)
	@make -C $(LIBFT_PATH) --no-print-directory
	@$(CC) $(CFLAGS) $(CLIENT_OBJS) -o $(CLIENT) $(LIBS)
	@echo "$(GREEN)[MINITALK] Client compiled successfully!$(DEF_COLOR)"

# Compiles C source files into object files
$(OBJS_PATH)%.o : $(SRCS_PATH)%.c
	@$(MKDIR) $(OBJS_PATH)
	@$(CC) $(CFLAGS) $(INCLUDES) -c $< -o $@
	@echo "$(BLUE)Compiling: $<$(DEF_COLOR)"

# Cleans object files and dependencies
clean :
	@$(REMOVE) $(OBJS_PATH) $(BONUS_OBJS_PATH)
	@make clean -C $(LIBFT_PATH) --no-print-directory
	@echo "$(BLUE)[MINITALK] Object files cleaned!$(DEF_COLOR)"

# Cleans everything generated by the Makefile
fclean : clean
	@$(REMOVE) $(SERVER) $(CLIENT)
	@make fclean -C $(LIBFT_PATH) --no-print-directory
	@echo "$(BLUE)[MINITALK] Executable files cleaned!$(DEF_COLOR)"

# Cleans everything generated by the Makefile and rebuild all
re : fclean all

# Phony targets
.PHONY : all clean fclean re